### YamlMime:ManagedReference
items:
- uid: Vibe_Game.Core.Settings
  commentId: N:Vibe_Game.Core.Settings
  id: Vibe_Game.Core.Settings
  children:
  - Vibe_Game.Core.Settings.CollectibleConfig
  - Vibe_Game.Core.Settings.EnemyConfig
  - Vibe_Game.Core.Settings.FloorConfig
  - Vibe_Game.Core.Settings.GameColors
  - Vibe_Game.Core.Settings.HealthHudConfig
  - Vibe_Game.Core.Settings.PedestalConfig
  - Vibe_Game.Core.Settings.PlayerConfig
  - Vibe_Game.Core.Settings.SoundConfig
  - Vibe_Game.Core.Settings.StartingWeaponConfig
  - Vibe_Game.Core.Settings.WeaponConfig
  - Vibe_Game.Core.Settings.WorldConfig
  langs:
  - csharp
  - vb
  name: Vibe_Game.Core.Settings
  nameWithType: Vibe_Game.Core.Settings
  fullName: Vibe_Game.Core.Settings
  type: Namespace
  assemblies:
  - Vibe_Game
references:
- uid: Vibe_Game.Core.Settings.WorldConfig
  commentId: T:Vibe_Game.Core.Settings.WorldConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.WorldConfig.html
  name: WorldConfig
  nameWithType: WorldConfig
  fullName: Vibe_Game.Core.Settings.WorldConfig
- uid: Vibe_Game.Core.Settings.FloorConfig
  commentId: T:Vibe_Game.Core.Settings.FloorConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.FloorConfig.html
  name: FloorConfig
  nameWithType: FloorConfig
  fullName: Vibe_Game.Core.Settings.FloorConfig
- uid: Vibe_Game.Core.Settings.PlayerConfig
  commentId: T:Vibe_Game.Core.Settings.PlayerConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.PlayerConfig.html
  name: PlayerConfig
  nameWithType: PlayerConfig
  fullName: Vibe_Game.Core.Settings.PlayerConfig
- uid: Vibe_Game.Core.Settings.EnemyConfig
  commentId: T:Vibe_Game.Core.Settings.EnemyConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.EnemyConfig.html
  name: EnemyConfig
  nameWithType: EnemyConfig
  fullName: Vibe_Game.Core.Settings.EnemyConfig
- uid: Vibe_Game.Core.Settings.WeaponConfig
  commentId: T:Vibe_Game.Core.Settings.WeaponConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.WeaponConfig.html
  name: WeaponConfig
  nameWithType: WeaponConfig
  fullName: Vibe_Game.Core.Settings.WeaponConfig
- uid: Vibe_Game.Core.Settings.CollectibleConfig
  commentId: T:Vibe_Game.Core.Settings.CollectibleConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.CollectibleConfig.html
  name: CollectibleConfig
  nameWithType: CollectibleConfig
  fullName: Vibe_Game.Core.Settings.CollectibleConfig
- uid: Vibe_Game.Core.Settings.PedestalConfig
  commentId: T:Vibe_Game.Core.Settings.PedestalConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.PedestalConfig.html
  name: PedestalConfig
  nameWithType: PedestalConfig
  fullName: Vibe_Game.Core.Settings.PedestalConfig
- uid: Vibe_Game.Core.Settings.StartingWeaponConfig
  commentId: T:Vibe_Game.Core.Settings.StartingWeaponConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.StartingWeaponConfig.html
  name: StartingWeaponConfig
  nameWithType: StartingWeaponConfig
  fullName: Vibe_Game.Core.Settings.StartingWeaponConfig
- uid: Vibe_Game.Core.Settings.HealthHudConfig
  commentId: T:Vibe_Game.Core.Settings.HealthHudConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.HealthHudConfig.html
  name: HealthHudConfig
  nameWithType: HealthHudConfig
  fullName: Vibe_Game.Core.Settings.HealthHudConfig
- uid: Vibe_Game.Core.Settings.SoundConfig
  commentId: T:Vibe_Game.Core.Settings.SoundConfig
  isExternal: true
  href: Vibe_Game.Core.Settings.SoundConfig.html
  name: SoundConfig
  nameWithType: SoundConfig
  fullName: Vibe_Game.Core.Settings.SoundConfig
- uid: Vibe_Game.Core.Settings.GameColors
  commentId: T:Vibe_Game.Core.Settings.GameColors
  isExternal: true
  href: Vibe_Game.Core.Settings.GameColors.html
  name: GameColors
  nameWithType: GameColors
  fullName: Vibe_Game.Core.Settings.GameColors
